# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://xieliuduo.github.io
date_format: "ordinal"
title: 山药豆的成长日记
subtitle: "编程改变人生"
description: "谢刘铎的个人博客"
keywords: 山药豆, xieliuduo, xliuduo, sheldonkk
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Liuduo Xie
organization: Sogou, Inc.
organization_url: https://www.sogou.com
location: Beijing, China
email: xliuduo@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xieliuduo/xieliuduo.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: xieliuduo


weibo_username: 路过夏末初秋
zhihu_username: 刘铎姓谢


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: xieliuduo
disqus_username: xieliuduo
# 在使用 disqus 的时候可点击显示多说评论框


# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [JavaScript, CSS, HTML, HTML5]
skill_mobile_app_keywords: [css3, HTML5 ,canvas]

